apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: kotlin-playground
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_DATASOURCE_PASSWORD: postgres
  JWT_SECRET: my-super-secret-key-that-is-at-least-256-bits-long-for-hs256
  API_KEYS: my-api-key-1,my-api-key-2
