apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: kotlin-playground
type: Opaque
stringData:
  POSTGRES_DB: playground
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
